/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsCategoryRouteImport } from './routes/collections.$category'
import { Route as ProductsProductSlugRouteImport } from './routes/products.$productSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCategoryRoute = CollectionsCategoryRouteImport.update({
  id: '/collections/$category',
  path: '/collections/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/products/$productSlug',
  path: '/products/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collections/$category' | '/products/$productSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collections/$category' | '/products/$productSlug'
  id: '__root__' | '/' | '/collections/$category' | '/products/$productSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsCategoryRoute: typeof CollectionsCategoryRoute
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$category': {
      id: '/collections/$category'
      path: '/collections/$category'
      fullPath: '/collections/$category'
      preLoaderRoute: typeof CollectionsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productSlug': {
      id: '/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/products/$productSlug'
      preLoaderRoute: typeof ProductsProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsCategoryRoute: CollectionsCategoryRoute,
  ProductsProductSlugRoute: ProductsProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
